# this file is sorted alphabetically using compose_format
# disable the restart:always line since we don't want it to start on the OS bootup

# the duplicate ${ENV_FILE} should be removed once --env-file works on docker-compose
# to run, create a .env file and use
# ENV_FILE=.env docker-compose -f docker-compose.prod.yml up --build

version: '3.7'
services:
  baseImage:
    image: base
    env_file: ${ENV_FILE}
    build: .

  backend:
    image: base
    command: >
      sh -c "npm run build:backend && npm run deploy:backend && npm run start:backend" 
    env_file: ${ENV_FILE}
    expose: 
      - 4001
    ports:
      - '4001:4001'
    depends_on:
      - prisma
    restart: always
    volumes:
      - ./deploy/certs:/deploy/certs

  frontend:
    image: base
    command: >
      sh -c 'npm run start:frontend'
    restart: always
    ports:
      - '8080:8080'
    env_file: ${ENV_FILE}
    volumes:
      - ./deploy/certs:/deploy/certs

  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/certs:/deploy/certs
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./deploy/nginx/proxy.conf:/etc/nginx/proxy.conf
    ports:
      - 80:80/tcp
      - 443:443/tcp
    links:
      - backend
    depends_on:
      - backend
    restart: always
    env_file: ${ENV_FILE}
 
  prisma:
    image: prismagraphql/prisma:1.34.8
    restart: always
    depends_on:
      - mysql
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            user: root
            password: prisma
            rawAccess: true
            port: 3306
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - ./persistence/mysql:/var/lib/mysql